/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.schctr.ui;

import com.schctr.lib.*;

import javax.swing.*;

/**
 *
 * @author 周明
 */
public class MainFrm extends JFrame {

    /**
     * 定义界面管理器对象
     */
    public static CMainFrm cmf = null;
    /**
     * 定义网络管理器对象
     */
    public static CNetWork cnw = null;
    /**
     * 定义线程池对象
     */
    public static CServerThreadPool cstp = null;
    /**
     * 定义网络消息队列对象
     */
    public static CDataSendQueue cdsq = null;
    /**
     * 定义系统日志生成器对象
     */
    public static CSysOptLog csol = null;
    /**
     * 定义文件管理器对象
     */
    public static CAppFileProc cafp = null;

    public MainFrm() {
        /**
         * 初始化各管理器实例
         */
        cmf = new CMainFrm();
        cnw = new CNetWork();
        cstp = new CServerThreadPool();
        cdsq = new CDataSendQueue();
        csol = new CSysOptLog();
        cafp = new CAppFileProc();

        cmf.initInstance(this);
        cstp.initInstance(10);
        cnw.initScheduleNet();
        /**
         * 更改系统字体
         */
        UIManager.put("swing.boldMetal", Boolean.FALSE);
        /**
         * 默认控件初始化
         */
        
        initComponents();

        /**
         * 初始化窗体加载后的信息
         */
        cmf.setAppIcon();
        cmf.actionRedrawProgressBar();
        cmf.initAppConfig();
        cmf.actionModelChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelControl = new javax.swing.JPanel();
        jPanelFileChose = new javax.swing.JPanel();
        jLabelFileChose = new javax.swing.JLabel();
        jButtonFileChose = new javax.swing.JButton();
        jTextFieldFileChose = new javax.swing.JTextField();
        jLabelFileParam = new javax.swing.JLabel();
        jTextFieldFileParam = new javax.swing.JTextField();
        jButtonVerifyFile = new javax.swing.JButton();
        jButtonFileSend = new javax.swing.JButton();
        jProgressBarSendFileProc = new javax.swing.JProgressBar();
        jLabelSendFileProc = new javax.swing.JLabel();
        jPanelModel = new javax.swing.JPanel();
        jLabelModelFile = new javax.swing.JLabel();
        jTextFieldModelFile = new javax.swing.JTextField();
        jButtonModelFile = new javax.swing.JButton();
        jPanelModelGraph = new javax.swing.JPanel();
        jLabelModelGraph = new javax.swing.JLabel();
        jButtonRun = new javax.swing.JButton();
        jPanelServerConfig = new javax.swing.JPanel();
        jLabelServerPort = new javax.swing.JLabel();
        jTextFieldServerPortOne = new javax.swing.JTextField();
        jLabelServerAddr = new javax.swing.JLabel();
        jTextFieldServerAddrOne = new javax.swing.JTextField();
        jLabelServer = new javax.swing.JLabel();
        jPanelServerClrOne = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldServerPowerOne = new javax.swing.JTextField();
        jLabelServerOpt = new javax.swing.JLabel();
        jButtonServerOptOne = new javax.swing.JButton();
        jLabelServerStatue = new javax.swing.JLabel();
        jLabelServerStatueOne = new javax.swing.JLabel();
        jPanelServerClrTwo = new javax.swing.JPanel();
        jTextFieldServerAddrTwo = new javax.swing.JTextField();
        jTextFieldServerPortTwo = new javax.swing.JTextField();
        jTextFieldServerPowerTwo = new javax.swing.JTextField();
        jLabelServerStatueTwo = new javax.swing.JLabel();
        jButtonServerOptTwo = new javax.swing.JButton();
        jPanelServerClrThr = new javax.swing.JPanel();
        jTextFieldServerAddrThr = new javax.swing.JTextField();
        jTextFieldServerPortThr = new javax.swing.JTextField();
        jTextFieldServerPowerThr = new javax.swing.JTextField();
        jLabelServerStatueThr = new javax.swing.JLabel();
        jButtonServerOptThr = new javax.swing.JButton();
        jPanelServer = new javax.swing.JPanel();
        jPanelServerStatue = new javax.swing.JPanel();
        jPanelJvmCpu = new javax.swing.JPanel();
        jLabelMacCpu = new javax.swing.JLabel();
        jProgressBarMacCpuOne = new javax.swing.JProgressBar();
        jProgressBarMacCpuTwo = new javax.swing.JProgressBar();
        jProgressBarMacCpuThr = new javax.swing.JProgressBar();
        jPanelMacMem = new javax.swing.JPanel();
        jLabelMacMem = new javax.swing.JLabel();
        jProgressBarMacMemOne = new javax.swing.JProgressBar();
        jProgressBarMacMemTwo = new javax.swing.JProgressBar();
        jProgressBarMacMemThr = new javax.swing.JProgressBar();
        jPanelJvmMem = new javax.swing.JPanel();
        jLabelJvmMem = new javax.swing.JLabel();
        jProgressBarJvmMemOne = new javax.swing.JProgressBar();
        jProgressBarJvmMemTwo = new javax.swing.JProgressBar();
        jProgressBarJvmMemThr = new javax.swing.JProgressBar();
        jPanelThread = new javax.swing.JPanel();
        jLabelThread = new javax.swing.JLabel();
        jProgressBarThreadOne = new javax.swing.JProgressBar();
        jProgressBarThreadTwo = new javax.swing.JProgressBar();
        jProgressBarThreadThr = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jPanelServerRunLog = new javax.swing.JPanel();
        jLabelServerRunLog = new javax.swing.JLabel();
        jScrollPaneRunLog = new javax.swing.JScrollPane();
        jTextAreaRunLog = new javax.swing.JTextArea();
        jMenuMain = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("云主机调度控制器");
        setName("MainFrm"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelFileChose.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelFileChose.setText("任务程序:");

        jButtonFileChose.setText("浏览");
        jButtonFileChose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFileChoseMouseClicked(evt);
            }
        });

        jTextFieldFileChose.setEditable(false);
        jTextFieldFileChose.setText("选择文件");
        jTextFieldFileChose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldFileChose.setFocusable(false);

        jLabelFileParam.setText("运行参数:");

        jButtonVerifyFile.setText("校验程序");
        jButtonVerifyFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVerifyFileMouseClicked(evt);
            }
        });

        jButtonFileSend.setText("发送程序");
        jButtonFileSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFileSendMouseClicked(evt);
            }
        });

        jProgressBarSendFileProc.setStringPainted(true);

        jLabelSendFileProc.setText("发送进度:");

        javax.swing.GroupLayout jPanelFileChoseLayout = new javax.swing.GroupLayout(jPanelFileChose);
        jPanelFileChose.setLayout(jPanelFileChoseLayout);
        jPanelFileChoseLayout.setHorizontalGroup(
            jPanelFileChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFileChoseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFileChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFileParam)
                    .addComponent(jLabelFileChose)
                    .addComponent(jLabelSendFileProc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFileChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFileChoseLayout.createSequentialGroup()
                        .addComponent(jTextFieldFileParam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFileSend))
                    .addGroup(jPanelFileChoseLayout.createSequentialGroup()
                        .addComponent(jTextFieldFileChose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFileChose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVerifyFile))
                    .addComponent(jProgressBarSendFileProc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelFileChoseLayout.setVerticalGroup(
            jPanelFileChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFileChoseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFileChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFileChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldFileChose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonFileChose)
                        .addComponent(jButtonVerifyFile))
                    .addComponent(jLabelFileChose, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFileChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldFileParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonFileSend))
                    .addComponent(jLabelFileParam, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFileChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSendFileProc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBarSendFileProc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFileChoseLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonFileChose, jButtonFileSend, jButtonVerifyFile, jTextFieldFileChose, jTextFieldFileParam});

        jPanelFileChoseLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelFileChose, jLabelFileParam, jLabelSendFileProc});

        jPanelModel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelModelFile.setText("配置文件:");

        jTextFieldModelFile.setEditable(false);
        jTextFieldModelFile.setText("选择文件");
        jTextFieldModelFile.setFocusable(false);

        jButtonModelFile.setText("浏览");
        jButtonModelFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonModelFileMouseClicked(evt);
            }
        });

        jPanelModelGraph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelModelGraph.setFocusable(false);

        javax.swing.GroupLayout jPanelModelGraphLayout = new javax.swing.GroupLayout(jPanelModelGraph);
        jPanelModelGraph.setLayout(jPanelModelGraphLayout);
        jPanelModelGraphLayout.setHorizontalGroup(
            jPanelModelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        jPanelModelGraphLayout.setVerticalGroup(
            jPanelModelGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jLabelModelGraph.setText("运行图像:");

        jButtonRun.setText("执行");
        jButtonRun.setEnabled(false);
        jButtonRun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRunMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelModelLayout = new javax.swing.GroupLayout(jPanelModel);
        jPanelModel.setLayout(jPanelModelLayout);
        jPanelModelLayout.setHorizontalGroup(
            jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModelFile)
                    .addComponent(jLabelModelGraph))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModelLayout.createSequentialGroup()
                        .addComponent(jTextFieldModelFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonModelFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRun))
                    .addComponent(jPanelModelGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanelModelLayout.setVerticalGroup(
            jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModelFile)
                    .addComponent(jTextFieldModelFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModelFile)
                    .addComponent(jButtonRun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModelGraph)
                    .addComponent(jPanelModelGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelModelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonModelFile, jLabelModelFile, jLabelModelGraph, jTextFieldModelFile});

        jPanelServerConfig.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelServerPort.setText("端口");

        jTextFieldServerPortOne.setText("8453");

        jLabelServerAddr.setText("IP地址");

        jTextFieldServerAddrOne.setText("000.000.000.000");
        jTextFieldServerAddrOne.setName(""); // NOI18N
        jTextFieldServerAddrOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldServerAddrOneMouseClicked(evt);
            }
        });

        jLabelServer.setText("服务器");

        jPanelServerClrOne.setBackground(new java.awt.Color(0, 204, 204));
        jPanelServerClrOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelServerClrOneLayout = new javax.swing.GroupLayout(jPanelServerClrOne);
        jPanelServerClrOne.setLayout(jPanelServerClrOneLayout);
        jPanelServerClrOneLayout.setHorizontalGroup(
            jPanelServerClrOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanelServerClrOneLayout.setVerticalGroup(
            jPanelServerClrOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabel1.setText("任务比");

        jTextFieldServerPowerOne.setText("0");

        jLabelServerOpt.setText("操作");

        jButtonServerOptOne.setText("连接");
        jButtonServerOptOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonServerOptOneMouseClicked(evt);
            }
        });

        jLabelServerStatue.setText("状态");

        jLabelServerStatueOne.setText("未连接");

        jPanelServerClrTwo.setBackground(new java.awt.Color(51, 0, 255));
        jPanelServerClrTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelServerClrTwoLayout = new javax.swing.GroupLayout(jPanelServerClrTwo);
        jPanelServerClrTwo.setLayout(jPanelServerClrTwoLayout);
        jPanelServerClrTwoLayout.setHorizontalGroup(
            jPanelServerClrTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanelServerClrTwoLayout.setVerticalGroup(
            jPanelServerClrTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jTextFieldServerAddrTwo.setText("000.000.000.000");
        jTextFieldServerAddrTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldServerAddrTwoMouseClicked(evt);
            }
        });

        jTextFieldServerPortTwo.setText("8453");

        jTextFieldServerPowerTwo.setText("0");

        jLabelServerStatueTwo.setText("未连接");
        jLabelServerStatueTwo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonServerOptTwo.setText("连接");
        jButtonServerOptTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonServerOptTwoMouseClicked(evt);
            }
        });

        jPanelServerClrThr.setBackground(new java.awt.Color(255, 0, 0));
        jPanelServerClrThr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelServerClrThrLayout = new javax.swing.GroupLayout(jPanelServerClrThr);
        jPanelServerClrThr.setLayout(jPanelServerClrThrLayout);
        jPanelServerClrThrLayout.setHorizontalGroup(
            jPanelServerClrThrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanelServerClrThrLayout.setVerticalGroup(
            jPanelServerClrThrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jTextFieldServerAddrThr.setText("000.000.000.000");
        jTextFieldServerAddrThr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldServerAddrThrMouseClicked(evt);
            }
        });

        jTextFieldServerPortThr.setText("8453");

        jTextFieldServerPowerThr.setText("0");

        jLabelServerStatueThr.setText("未连接");
        jLabelServerStatueThr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonServerOptThr.setText("连接");
        jButtonServerOptThr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonServerOptThrMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelServerConfigLayout = new javax.swing.GroupLayout(jPanelServerConfig);
        jPanelServerConfig.setLayout(jPanelServerConfigLayout);
        jPanelServerConfigLayout.setHorizontalGroup(
            jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServerConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelServer)
                    .addComponent(jPanelServerClrOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelServerClrTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelServerClrThr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelServerAddr)
                    .addComponent(jTextFieldServerAddrOne, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerAddrTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerAddrThr, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelServerPort)
                    .addComponent(jTextFieldServerPortOne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerPortTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerPortThr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldServerPowerOne, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerPowerTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerPowerThr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelServerStatue)
                    .addComponent(jLabelServerStatueOne, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServerStatueTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServerStatueThr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelServerOpt)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelServerConfigLayout.createSequentialGroup()
                        .addGroup(jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButtonServerOptOne, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(jButtonServerOptTwo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonServerOptThr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanelServerConfigLayout.setVerticalGroup(
            jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServerConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServerAddr)
                    .addComponent(jLabelServer)
                    .addComponent(jLabel1)
                    .addComponent(jLabelServerOpt)
                    .addComponent(jLabelServerStatue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldServerPortOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerAddrOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelServerClrOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerPowerOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonServerOptOne)
                    .addComponent(jLabelServerStatueOne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldServerPortTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerAddrTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelServerClrTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerPowerTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonServerOptTwo)
                    .addComponent(jLabelServerStatueTwo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelServerConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldServerPortThr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerAddrThr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelServerClrThr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServerPowerThr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonServerOptThr)
                    .addComponent(jLabelServerStatueThr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelServerConfigLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabelServer, jLabelServerAddr, jLabelServerOpt, jLabelServerPort, jLabelServerStatue});

        jPanelServerConfigLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelServerStatueOne, jTextFieldServerPowerOne});

        javax.swing.GroupLayout jPanelControlLayout = new javax.swing.GroupLayout(jPanelControl);
        jPanelControl.setLayout(jPanelControlLayout);
        jPanelControlLayout.setHorizontalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelServerConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFileChose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelControlLayout.setVerticalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFileChose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelServerConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelServer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelServerStatue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelJvmCpu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelJvmCpu.setFocusable(false);

        jLabelMacCpu.setText("MAC-CPU");

        jProgressBarMacCpuOne.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarMacCpuOne.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBarMacCpuOne.setBorderPainted(false);
        jProgressBarMacCpuOne.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarMacCpuOne.setFocusable(false);
        jProgressBarMacCpuOne.setName(""); // NOI18N
        jProgressBarMacCpuOne.setString("0");
        jProgressBarMacCpuOne.setStringPainted(true);

        jProgressBarMacCpuTwo.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarMacCpuTwo.setForeground(new java.awt.Color(0, 0, 255));
        jProgressBarMacCpuTwo.setBorderPainted(false);
        jProgressBarMacCpuTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarMacCpuTwo.setFocusable(false);
        jProgressBarMacCpuTwo.setName(""); // NOI18N
        jProgressBarMacCpuTwo.setString("0");
        jProgressBarMacCpuTwo.setStringPainted(true);

        jProgressBarMacCpuThr.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarMacCpuThr.setForeground(new java.awt.Color(255, 0, 0));
        jProgressBarMacCpuThr.setBorderPainted(false);
        jProgressBarMacCpuThr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarMacCpuThr.setFocusable(false);
        jProgressBarMacCpuThr.setName(""); // NOI18N
        jProgressBarMacCpuThr.setString("0");
        jProgressBarMacCpuThr.setStringPainted(true);

        javax.swing.GroupLayout jPanelJvmCpuLayout = new javax.swing.GroupLayout(jPanelJvmCpu);
        jPanelJvmCpu.setLayout(jPanelJvmCpuLayout);
        jPanelJvmCpuLayout.setHorizontalGroup(
            jPanelJvmCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJvmCpuLayout.createSequentialGroup()
                .addComponent(jLabelMacCpu)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jProgressBarMacCpuOne, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addComponent(jProgressBarMacCpuTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jProgressBarMacCpuThr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelJvmCpuLayout.setVerticalGroup(
            jPanelJvmCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJvmCpuLayout.createSequentialGroup()
                .addComponent(jLabelMacCpu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarMacCpuOne, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBarMacCpuTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBarMacCpuThr, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelMacMem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelMacMem.setText("MAC-Mem");

        jProgressBarMacMemOne.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarMacMemOne.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBarMacMemOne.setBorderPainted(false);
        jProgressBarMacMemOne.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarMacMemOne.setFocusable(false);
        jProgressBarMacMemOne.setName(""); // NOI18N
        jProgressBarMacMemOne.setString("0/0MB");
        jProgressBarMacMemOne.setStringPainted(true);

        jProgressBarMacMemTwo.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarMacMemTwo.setForeground(new java.awt.Color(0, 0, 255));
        jProgressBarMacMemTwo.setBorderPainted(false);
        jProgressBarMacMemTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarMacMemTwo.setFocusable(false);
        jProgressBarMacMemTwo.setName(""); // NOI18N
        jProgressBarMacMemTwo.setString("0/0MB");
        jProgressBarMacMemTwo.setStringPainted(true);

        jProgressBarMacMemThr.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarMacMemThr.setForeground(new java.awt.Color(255, 0, 0));
        jProgressBarMacMemThr.setBorderPainted(false);
        jProgressBarMacMemThr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarMacMemThr.setFocusable(false);
        jProgressBarMacMemThr.setName(""); // NOI18N
        jProgressBarMacMemThr.setString("0/0MB");
        jProgressBarMacMemThr.setStringPainted(true);

        javax.swing.GroupLayout jPanelMacMemLayout = new javax.swing.GroupLayout(jPanelMacMem);
        jPanelMacMem.setLayout(jPanelMacMemLayout);
        jPanelMacMemLayout.setHorizontalGroup(
            jPanelMacMemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMacMemLayout.createSequentialGroup()
                .addComponent(jLabelMacMem)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jProgressBarMacMemOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jProgressBarMacMemTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jProgressBarMacMemThr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMacMemLayout.setVerticalGroup(
            jPanelMacMemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMacMemLayout.createSequentialGroup()
                .addComponent(jLabelMacMem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarMacMemOne, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBarMacMemTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBarMacMemThr, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelJvmMem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelJvmMem.setText("JVM-Mem");

        jProgressBarJvmMemOne.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarJvmMemOne.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBarJvmMemOne.setBorderPainted(false);
        jProgressBarJvmMemOne.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarJvmMemOne.setFocusable(false);
        jProgressBarJvmMemOne.setName(""); // NOI18N
        jProgressBarJvmMemOne.setString("0/0MB");
        jProgressBarJvmMemOne.setStringPainted(true);

        jProgressBarJvmMemTwo.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarJvmMemTwo.setForeground(new java.awt.Color(0, 0, 255));
        jProgressBarJvmMemTwo.setBorderPainted(false);
        jProgressBarJvmMemTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarJvmMemTwo.setFocusable(false);
        jProgressBarJvmMemTwo.setName(""); // NOI18N
        jProgressBarJvmMemTwo.setString("0/0MB");
        jProgressBarJvmMemTwo.setStringPainted(true);

        jProgressBarJvmMemThr.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarJvmMemThr.setForeground(new java.awt.Color(255, 0, 0));
        jProgressBarJvmMemThr.setBorderPainted(false);
        jProgressBarJvmMemThr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarJvmMemThr.setFocusable(false);
        jProgressBarJvmMemThr.setName(""); // NOI18N
        jProgressBarJvmMemThr.setString("0/0MB");
        jProgressBarJvmMemThr.setStringPainted(true);

        javax.swing.GroupLayout jPanelJvmMemLayout = new javax.swing.GroupLayout(jPanelJvmMem);
        jPanelJvmMem.setLayout(jPanelJvmMemLayout);
        jPanelJvmMemLayout.setHorizontalGroup(
            jPanelJvmMemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJvmMemLayout.createSequentialGroup()
                .addComponent(jLabelJvmMem)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jProgressBarJvmMemOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jProgressBarJvmMemTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jProgressBarJvmMemThr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelJvmMemLayout.setVerticalGroup(
            jPanelJvmMemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJvmMemLayout.createSequentialGroup()
                .addComponent(jLabelJvmMem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarJvmMemOne, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBarJvmMemTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBarJvmMemThr, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanelThread.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelThread.setText("Thread");

        jProgressBarThreadOne.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarThreadOne.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBarThreadOne.setBorderPainted(false);
        jProgressBarThreadOne.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarThreadOne.setFocusable(false);
        jProgressBarThreadOne.setName(""); // NOI18N
        jProgressBarThreadOne.setString("0");
        jProgressBarThreadOne.setStringPainted(true);

        jProgressBarThreadTwo.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarThreadTwo.setForeground(new java.awt.Color(0, 0, 255));
        jProgressBarThreadTwo.setBorderPainted(false);
        jProgressBarThreadTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarThreadTwo.setFocusable(false);
        jProgressBarThreadTwo.setName(""); // NOI18N
        jProgressBarThreadTwo.setString("0");
        jProgressBarThreadTwo.setStringPainted(true);

        jProgressBarThreadThr.setBackground(new java.awt.Color(153, 153, 153));
        jProgressBarThreadThr.setForeground(new java.awt.Color(255, 0, 0));
        jProgressBarThreadThr.setBorderPainted(false);
        jProgressBarThreadThr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarThreadThr.setFocusable(false);
        jProgressBarThreadThr.setName(""); // NOI18N
        jProgressBarThreadThr.setString("0");
        jProgressBarThreadThr.setStringPainted(true);

        javax.swing.GroupLayout jPanelThreadLayout = new javax.swing.GroupLayout(jPanelThread);
        jPanelThread.setLayout(jPanelThreadLayout);
        jPanelThreadLayout.setHorizontalGroup(
            jPanelThreadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThreadLayout.createSequentialGroup()
                .addComponent(jLabelThread)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jProgressBarThreadOne, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
            .addComponent(jProgressBarThreadTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jProgressBarThreadThr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelThreadLayout.setVerticalGroup(
            jPanelThreadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThreadLayout.createSequentialGroup()
                .addComponent(jLabelThread)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarThreadOne, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBarThreadTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBarThreadThr, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelServerStatueLayout = new javax.swing.GroupLayout(jPanelServerStatue);
        jPanelServerStatue.setLayout(jPanelServerStatueLayout);
        jPanelServerStatueLayout.setHorizontalGroup(
            jPanelServerStatueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServerStatueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServerStatueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelJvmCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelJvmMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelServerStatueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelThread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMacMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelServerStatueLayout.setVerticalGroup(
            jPanelServerStatueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelServerStatueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServerStatueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelJvmCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelThread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelServerStatueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelJvmMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMacMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );

        jLabel2.setText("服务器状态:");

        jPanelServerRunLog.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelServerRunLog.setText("执行日志:");

        jTextAreaRunLog.setColumns(20);
        jTextAreaRunLog.setRows(5);
        jTextAreaRunLog.setFocusable(false);
        jScrollPaneRunLog.setViewportView(jTextAreaRunLog);

        javax.swing.GroupLayout jPanelServerRunLogLayout = new javax.swing.GroupLayout(jPanelServerRunLog);
        jPanelServerRunLog.setLayout(jPanelServerRunLogLayout);
        jPanelServerRunLogLayout.setHorizontalGroup(
            jPanelServerRunLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServerRunLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServerRunLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelServerRunLogLayout.createSequentialGroup()
                        .addComponent(jLabelServerRunLog)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPaneRunLog))
                .addContainerGap())
        );
        jPanelServerRunLogLayout.setVerticalGroup(
            jPanelServerRunLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServerRunLogLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelServerRunLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneRunLog, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelServerLayout = new javax.swing.GroupLayout(jPanelServer);
        jPanelServer.setLayout(jPanelServerLayout);
        jPanelServerLayout.setHorizontalGroup(
            jPanelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelServerStatue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelServerLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelServerRunLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelServerLayout.setVerticalGroup(
            jPanelServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServerLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanelServerRunLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelServerStatue, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuMain.setMinimumSize(new java.awt.Dimension(35, 19));

        jMenuFile.setText("文件");
        jMenuFile.setMaximumSize(new java.awt.Dimension(50, 32767));
        jMenuFile.setMinimumSize(new java.awt.Dimension(35, 21));
        jMenuFile.setPreferredSize(new java.awt.Dimension(35, 21));
        jMenuMain.add(jMenuFile);

        setJMenuBar(jMenuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setBounds(0, 0, 886, 557);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFileChoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFileChoseMouseClicked
        // TODO add your handling code here:
        MainFrm.cmf.actionChoseProcFile();
    }//GEN-LAST:event_jButtonFileChoseMouseClicked

    private void jButtonModelFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModelFileMouseClicked
        // TODO add your handling code here:
        MainFrm.cmf.actionChoseXmlFile();
    }//GEN-LAST:event_jButtonModelFileMouseClicked

    private void jTextFieldServerAddrOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldServerAddrOneMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldServerAddrOne.getText().equals("000.000.000.000")) {
            this.jTextFieldServerAddrOne.setText("");
        }
    }//GEN-LAST:event_jTextFieldServerAddrOneMouseClicked

    private void jTextFieldServerAddrTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldServerAddrTwoMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldServerAddrTwo.getText().equals("000.000.000.000")) {
            this.jTextFieldServerAddrTwo.setText("");
        }
    }//GEN-LAST:event_jTextFieldServerAddrTwoMouseClicked

    private void jTextFieldServerAddrThrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldServerAddrThrMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldServerAddrThr.getText().equals("000.000.000.000")) {
            this.jTextFieldServerAddrThr.setText("");
        }
    }//GEN-LAST:event_jTextFieldServerAddrThrMouseClicked

    private void jButtonServerOptOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonServerOptOneMouseClicked
        // TODO add your handling code here:
        cmf.actionServerLink(0);
    }//GEN-LAST:event_jButtonServerOptOneMouseClicked

    private void jButtonServerOptTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonServerOptTwoMouseClicked
        // TODO add your handling code here:
        cmf.actionServerLink(1);
    }//GEN-LAST:event_jButtonServerOptTwoMouseClicked

    private void jButtonServerOptThrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonServerOptThrMouseClicked
        // TODO add your handling code here:
        cmf.actionServerLink(2);
    }//GEN-LAST:event_jButtonServerOptThrMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cnw.closeAll();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonVerifyFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVerifyFileMouseClicked
        // TODO add your handling code here:
        cmf.actionVerifyFile();
    }//GEN-LAST:event_jButtonVerifyFileMouseClicked

    private void jButtonFileSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFileSendMouseClicked
        // TODO add your handling code here:
        cmf.actionSendFileProc();
    }//GEN-LAST:event_jButtonFileSendMouseClicked

    private void jButtonRunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRunMouseClicked
        // TODO add your handling code here:
        if(!this.jButtonRun.isEnabled()){
            return ;
        }
        cmf.actionRun();
    }//GEN-LAST:event_jButtonRunMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrm().setVisible(true);
            }
        });
    }

    public JButton getjButtonFileCheck() {
        return jButtonVerifyFile;
    }

    public void setjButtonFileCheck(JButton jButtonFileCheck) {
        this.jButtonVerifyFile = jButtonFileCheck;
    }

    public JButton getjButtonFileChose() {
        return jButtonFileChose;
    }

    public void setjButtonFileChose(JButton jButtonFileChose) {
        this.jButtonFileChose = jButtonFileChose;
    }

    public JButton getjButtonFileSend() {
        return jButtonFileSend;
    }

    public void setjButtonFileSend(JButton jButtonFileSend) {
        this.jButtonFileSend = jButtonFileSend;
    }

    public JButton getjButtonModelFile() {
        return jButtonModelFile;
    }

    public void setjButtonModelFile(JButton jButtonModelFile) {
        this.jButtonModelFile = jButtonModelFile;
    }

    public JButton getjButtonRun() {
        return jButtonRun;
    }

    public void setjButtonRun(JButton jButtonRun) {
        this.jButtonRun = jButtonRun;
    }

    public JButton getjButtonServerOptOne() {
        return jButtonServerOptOne;
    }

    public void setjButtonServerOptOne(JButton jButtonServerOptOne) {
        this.jButtonServerOptOne = jButtonServerOptOne;
    }

    public JButton getjButtonServerOptThr() {
        return jButtonServerOptThr;
    }

    public void setjButtonServerOptThr(JButton jButtonServerOptThr) {
        this.jButtonServerOptThr = jButtonServerOptThr;
    }

    public JButton getjButtonServerOptTwo() {
        return jButtonServerOptTwo;
    }

    public void setjButtonServerOptTwo(JButton jButtonServerOptTwo) {
        this.jButtonServerOptTwo = jButtonServerOptTwo;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabelFileChose() {
        return jLabelFileChose;
    }

    public void setjLabelFileChose(JLabel jLabelFileChose) {
        this.jLabelFileChose = jLabelFileChose;
    }

    public JLabel getjLabelFileParam() {
        return jLabelFileParam;
    }

    public void setjLabelFileParam(JLabel jLabelFileParam) {
        this.jLabelFileParam = jLabelFileParam;
    }

    public JLabel getjLabelModelFile() {
        return jLabelModelFile;
    }

    public void setjLabelModelFile(JLabel jLabelModelFile) {
        this.jLabelModelFile = jLabelModelFile;
    }

    public JLabel getjLabelModelGraph() {
        return jLabelModelGraph;
    }

    public void setjLabelModelGraph(JLabel jLabelModelGraph) {
        this.jLabelModelGraph = jLabelModelGraph;
    }

    public JLabel getjLabelServer() {
        return jLabelServer;
    }

    public void setjLabelServer(JLabel jLabelServer) {
        this.jLabelServer = jLabelServer;
    }

    public JLabel getjLabelServerAddr() {
        return jLabelServerAddr;
    }

    public void setjLabelServerAddr(JLabel jLabelServerAddr) {
        this.jLabelServerAddr = jLabelServerAddr;
    }

    public JLabel getjLabelServerOpt() {
        return jLabelServerOpt;
    }

    public void setjLabelServerOpt(JLabel jLabelServerOpt) {
        this.jLabelServerOpt = jLabelServerOpt;
    }

    public JLabel getjLabelServerPort() {
        return jLabelServerPort;
    }

    public void setjLabelServerPort(JLabel jLabelServerPort) {
        this.jLabelServerPort = jLabelServerPort;
    }

    public JLabel getjLabelServerRunLog() {
        return jLabelServerRunLog;
    }

    public void setjLabelServerRunLog(JLabel jLabelServerRunLog) {
        this.jLabelServerRunLog = jLabelServerRunLog;
    }

    public JLabel getjLabelServerStatue() {
        return jLabelServerStatue;
    }

    public void setjLabelServerStatue(JLabel jLabelServerStatue) {
        this.jLabelServerStatue = jLabelServerStatue;
    }

    public JLabel getjLabelServerStatueOne() {
        return jLabelServerStatueOne;
    }

    public void setjLabelServerStatueOne(JLabel jLabelServerStatueOne) {
        this.jLabelServerStatueOne = jLabelServerStatueOne;
    }

    public JLabel getjLabelServerStatueThr() {
        return jLabelServerStatueThr;
    }

    public void setjLabelServerStatueThr(JLabel jLabelServerStatueThr) {
        this.jLabelServerStatueThr = jLabelServerStatueThr;
    }

    public JLabel getjLabelServerStatueTwo() {
        return jLabelServerStatueTwo;
    }

    public void setjLabelServerStatueTwo(JLabel jLabelServerStatueTwo) {
        this.jLabelServerStatueTwo = jLabelServerStatueTwo;
    }

    public JPanel getjPanelControl() {
        return jPanelControl;
    }

    public void setjPanelControl(JPanel jPanelControl) {
        this.jPanelControl = jPanelControl;
    }

    public JPanel getjPanelFileChose() {
        return jPanelFileChose;
    }

    public void setjPanelFileChose(JPanel jPanelFileChose) {
        this.jPanelFileChose = jPanelFileChose;
    }

    public JPanel getjPanelModel() {
        return jPanelModel;
    }

    public void setjPanelModel(JPanel jPanelModel) {
        this.jPanelModel = jPanelModel;
    }

    public JPanel getjPanelModelGraph() {
        return jPanelModelGraph;
    }

    public void setjPanelModelGraph(JPanel jPanelModelGraph) {
        this.jPanelModelGraph = jPanelModelGraph;
    }

    public JPanel getjPanelServer() {
        return jPanelServer;
    }

    public void setjPanelServer(JPanel jPanelServer) {
        this.jPanelServer = jPanelServer;
    }

    public JPanel getjPanelServerClrOne() {
        return jPanelServerClrOne;
    }

    public void setjPanelServerClrOne(JPanel jPanelServerClrOne) {
        this.jPanelServerClrOne = jPanelServerClrOne;
    }

    public JPanel getjPanelServerClrThr() {
        return jPanelServerClrThr;
    }

    public void setjPanelServerClrThr(JPanel jPanelServerClrThr) {
        this.jPanelServerClrThr = jPanelServerClrThr;
    }

    public JPanel getjPanelServerClrTwo() {
        return jPanelServerClrTwo;
    }

    public void setjPanelServerClrTwo(JPanel jPanelServerClrTwo) {
        this.jPanelServerClrTwo = jPanelServerClrTwo;
    }

    public JPanel getjPanelServerConfig() {
        return jPanelServerConfig;
    }

    public void setjPanelServerConfig(JPanel jPanelServerConfig) {
        this.jPanelServerConfig = jPanelServerConfig;
    }

    public JPanel getjPanelServerCpu() {
        return jPanelMacMem;
    }

    public void setjPanelServerCpu(JPanel jPanelServerCpu) {
        this.jPanelMacMem = jPanelServerCpu;
    }

    public JPanel getjPanelServerRunLog() {
        return jPanelServerRunLog;
    }

    public void setjPanelServerRunLog(JPanel jPanelServerRunLog) {
        this.jPanelServerRunLog = jPanelServerRunLog;
    }

    public JPanel getjPanelServerStatue() {
        return jPanelServerStatue;
    }

    public void setjPanelServerStatue(JPanel jPanelServerStatue) {
        this.jPanelServerStatue = jPanelServerStatue;
    }

    public JScrollPane getjScrollPaneRunLog() {
        return jScrollPaneRunLog;
    }

    public void setjScrollPaneRunLog(JScrollPane jScrollPaneRunLog) {
        this.jScrollPaneRunLog = jScrollPaneRunLog;
    }

    public JTextArea getjTextAreaRunLog() {
        return jTextAreaRunLog;
    }

    public void setjTextAreaRunLog(JTextArea jTextAreaRunLog) {
        this.jTextAreaRunLog = jTextAreaRunLog;
    }

    public JTextField getjTextFieldFileChose() {
        return jTextFieldFileChose;
    }

    public void setjTextFieldFileChose(JTextField jTextFieldFileChose) {
        this.jTextFieldFileChose = jTextFieldFileChose;
    }

    public JTextField getjTextFieldFileParam() {
        return jTextFieldFileParam;
    }

    public void setjTextFieldFileParam(JTextField jTextFieldFileParam) {
        this.jTextFieldFileParam = jTextFieldFileParam;
    }

    public JTextField getjTextFieldModelFile() {
        return jTextFieldModelFile;
    }

    public void setjTextFieldModelFile(JTextField jTextFieldModelFile) {
        this.jTextFieldModelFile = jTextFieldModelFile;
    }

    public JTextField getjTextFieldServerAddrOne() {
        return jTextFieldServerAddrOne;
    }

    public void setjTextFieldServerAddrOne(JTextField jTextFieldServerAddrOne) {
        this.jTextFieldServerAddrOne = jTextFieldServerAddrOne;
    }

    public JTextField getjTextFieldServerAddrThr() {
        return jTextFieldServerAddrThr;
    }

    public void setjTextFieldServerAddrThr(JTextField jTextFieldServerAddrThr) {
        this.jTextFieldServerAddrThr = jTextFieldServerAddrThr;
    }

    public JTextField getjTextFieldServerAddrTwo() {
        return jTextFieldServerAddrTwo;
    }

    public void setjTextFieldServerAddrTwo(JTextField jTextFieldServerAddrTwo) {
        this.jTextFieldServerAddrTwo = jTextFieldServerAddrTwo;
    }

    public JTextField getjTextFieldServerPortOne() {
        return jTextFieldServerPortOne;
    }

    public void setjTextFieldServerPortOne(JTextField jTextFieldServerPortOne) {
        this.jTextFieldServerPortOne = jTextFieldServerPortOne;
    }

    public JTextField getjTextFieldServerPortThr() {
        return jTextFieldServerPortThr;
    }

    public void setjTextFieldServerPortThr(JTextField jTextFieldServerPortThr) {
        this.jTextFieldServerPortThr = jTextFieldServerPortThr;
    }

    public JTextField getjTextFieldServerPortTwo() {
        return jTextFieldServerPortTwo;
    }

    public void setjTextFieldServerPortTwo(JTextField jTextFieldServerPortTwo) {
        this.jTextFieldServerPortTwo = jTextFieldServerPortTwo;
    }

    public JTextField getjTextFieldServerPowerOne() {
        return jTextFieldServerPowerOne;
    }

    public void setjTextFieldServerPowerOne(JTextField jTextFieldServerPowerOne) {
        this.jTextFieldServerPowerOne = jTextFieldServerPowerOne;
    }

    public JTextField getjTextFieldServerPowerThr() {
        return jTextFieldServerPowerThr;
    }

    public void setjTextFieldServerPowerThr(JTextField jTextFieldServerPowerThr) {
        this.jTextFieldServerPowerThr = jTextFieldServerPowerThr;
    }

    public JTextField getjTextFieldServerPowerTwo() {
        return jTextFieldServerPowerTwo;
    }

    public void setjTextFieldServerPowerTwo(JTextField jTextFieldServerPowerTwo) {
        this.jTextFieldServerPowerTwo = jTextFieldServerPowerTwo;
    }

    public JProgressBar getjProgressBarMacCpuOne() {
        return jProgressBarMacCpuOne;
    }

    public void setjProgressBarMacCpuOne(JProgressBar jProgressBarMacCpuOne) {
        this.jProgressBarMacCpuOne = jProgressBarMacCpuOne;
    }

    public JProgressBar getjProgressBarMacCpuThr() {
        return jProgressBarMacCpuThr;
    }

    public void setjProgressBarMacCpuThr(JProgressBar jProgressBarMacCpuThr) {
        this.jProgressBarMacCpuThr = jProgressBarMacCpuThr;
    }

    public JProgressBar getjProgressBarMacCpuTwo() {
        return jProgressBarMacCpuTwo;
    }

    public void setjProgressBarMacCpuTwo(JProgressBar jProgressBarMacCpuTwo) {
        this.jProgressBarMacCpuTwo = jProgressBarMacCpuTwo;
    }

    public JProgressBar getjProgressBarJvmMemOne() {
        return jProgressBarJvmMemOne;
    }

    public void setjProgressBarJvmMemOne(JProgressBar jProgressBarJvmMemOne) {
        this.jProgressBarJvmMemOne = jProgressBarJvmMemOne;
    }

    public JProgressBar getjProgressBarJvmMemThr() {
        return jProgressBarJvmMemThr;
    }

    public void setjProgressBarJvmMemThr(JProgressBar jProgressBarJvmMemThr) {
        this.jProgressBarJvmMemThr = jProgressBarJvmMemThr;
    }

    public JProgressBar getjProgressBarJvmMemTwo() {
        return jProgressBarJvmMemTwo;
    }

    public void setjProgressBarJvmMemTwo(JProgressBar jProgressBarJvmMemTwo) {
        this.jProgressBarJvmMemTwo = jProgressBarJvmMemTwo;
    }

    public JProgressBar getjProgressBarThreadOne() {
        return jProgressBarThreadOne;
    }

    public void setjProgressBarThreadOne(JProgressBar jProgressBarThreadOne) {
        this.jProgressBarThreadOne = jProgressBarThreadOne;
    }

    public JProgressBar getjProgressBarThreadThr() {
        return jProgressBarThreadThr;
    }

    public void setjProgressBarThreadThr(JProgressBar jProgressBarThreadThr) {
        this.jProgressBarThreadThr = jProgressBarThreadThr;
    }

    public JProgressBar getjProgressBarThreadTwo() {
        return jProgressBarThreadTwo;
    }

    public void setjProgressBarThreadTwo(JProgressBar jProgressBarThreadTwo) {
        this.jProgressBarThreadTwo = jProgressBarThreadTwo;
    }

    public JProgressBar getjProgressBarMacMemOne() {
        return jProgressBarMacMemOne;
    }

    public void setjProgressBarMacMemOne(JProgressBar jProgressBarMacMemOne) {
        this.jProgressBarMacMemOne = jProgressBarMacMemOne;
    }

    public JProgressBar getjProgressBarMacMemThr() {
        return jProgressBarMacMemThr;
    }

    public void setjProgressBarMacMemThr(JProgressBar jProgressBarMacMemThr) {
        this.jProgressBarMacMemThr = jProgressBarMacMemThr;
    }

    public JProgressBar getjProgressBarMacMemTwo() {
        return jProgressBarMacMemTwo;
    }

    public void setjProgressBarMacMemTwo(JProgressBar jProgressBarMacMemTwo) {
        this.jProgressBarMacMemTwo = jProgressBarMacMemTwo;
    }

    public JProgressBar getjProgressBarSendFileProc() {
        return jProgressBarSendFileProc;
    }

    public void setjProgressBarSendFileProc(JProgressBar jProgressBarSendFileProc) {
        this.jProgressBarSendFileProc = jProgressBarSendFileProc;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFileChose;
    private javax.swing.JButton jButtonFileSend;
    private javax.swing.JButton jButtonModelFile;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JButton jButtonServerOptOne;
    private javax.swing.JButton jButtonServerOptThr;
    private javax.swing.JButton jButtonServerOptTwo;
    private javax.swing.JButton jButtonVerifyFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFileChose;
    private javax.swing.JLabel jLabelFileParam;
    private javax.swing.JLabel jLabelJvmMem;
    private javax.swing.JLabel jLabelMacCpu;
    private javax.swing.JLabel jLabelMacMem;
    private javax.swing.JLabel jLabelModelFile;
    private javax.swing.JLabel jLabelModelGraph;
    private javax.swing.JLabel jLabelSendFileProc;
    private javax.swing.JLabel jLabelServer;
    private javax.swing.JLabel jLabelServerAddr;
    private javax.swing.JLabel jLabelServerOpt;
    private javax.swing.JLabel jLabelServerPort;
    private javax.swing.JLabel jLabelServerRunLog;
    private javax.swing.JLabel jLabelServerStatue;
    private javax.swing.JLabel jLabelServerStatueOne;
    private javax.swing.JLabel jLabelServerStatueThr;
    private javax.swing.JLabel jLabelServerStatueTwo;
    private javax.swing.JLabel jLabelThread;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuBar jMenuMain;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelFileChose;
    private javax.swing.JPanel jPanelJvmCpu;
    private javax.swing.JPanel jPanelJvmMem;
    private javax.swing.JPanel jPanelMacMem;
    private javax.swing.JPanel jPanelModel;
    private javax.swing.JPanel jPanelModelGraph;
    private javax.swing.JPanel jPanelServer;
    private javax.swing.JPanel jPanelServerClrOne;
    private javax.swing.JPanel jPanelServerClrThr;
    private javax.swing.JPanel jPanelServerClrTwo;
    private javax.swing.JPanel jPanelServerConfig;
    private javax.swing.JPanel jPanelServerRunLog;
    private javax.swing.JPanel jPanelServerStatue;
    private javax.swing.JPanel jPanelThread;
    private javax.swing.JProgressBar jProgressBarJvmMemOne;
    private javax.swing.JProgressBar jProgressBarJvmMemThr;
    private javax.swing.JProgressBar jProgressBarJvmMemTwo;
    private javax.swing.JProgressBar jProgressBarMacCpuOne;
    private javax.swing.JProgressBar jProgressBarMacCpuThr;
    private javax.swing.JProgressBar jProgressBarMacCpuTwo;
    private javax.swing.JProgressBar jProgressBarMacMemOne;
    private javax.swing.JProgressBar jProgressBarMacMemThr;
    private javax.swing.JProgressBar jProgressBarMacMemTwo;
    private javax.swing.JProgressBar jProgressBarSendFileProc;
    private javax.swing.JProgressBar jProgressBarThreadOne;
    private javax.swing.JProgressBar jProgressBarThreadThr;
    private javax.swing.JProgressBar jProgressBarThreadTwo;
    private javax.swing.JScrollPane jScrollPaneRunLog;
    private javax.swing.JTextArea jTextAreaRunLog;
    private javax.swing.JTextField jTextFieldFileChose;
    private javax.swing.JTextField jTextFieldFileParam;
    private javax.swing.JTextField jTextFieldModelFile;
    private javax.swing.JTextField jTextFieldServerAddrOne;
    private javax.swing.JTextField jTextFieldServerAddrThr;
    private javax.swing.JTextField jTextFieldServerAddrTwo;
    private javax.swing.JTextField jTextFieldServerPortOne;
    private javax.swing.JTextField jTextFieldServerPortThr;
    private javax.swing.JTextField jTextFieldServerPortTwo;
    private javax.swing.JTextField jTextFieldServerPowerOne;
    private javax.swing.JTextField jTextFieldServerPowerThr;
    private javax.swing.JTextField jTextFieldServerPowerTwo;
    // End of variables declaration//GEN-END:variables
}
